import { Inter } from "next/font/google";
import "./globals.css";
import Navbar  from "@/components/Navbar";
import Footer from "@/components/Footer";

import toast, { Toaster } from 'react-hot-toast';
import Session from "@/components/Session";
import { ThemeProvider } from "../context/ThemeProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <ThemeProvider>
      <Session>
      <div className="flex flex-col h-screen justify-between px-3 md:px-10 w-full text-[#bbb]">
        <Navbar/>
          {children}
        <Footer/>
        </div>
        <Toaster
          position="top-center"
          reverseOrder={false}
        />
      </Session>
      </ThemeProvider>
     

        </body>
    </html>
  );
}
